name: shirakiya-test-action
author: shirakiya
description: My custom action for test.
runs:
  using: 'composite'
  steps:
      - name: echo
        run: echo "Hello world! This is tag"
        shell: bash
